/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.65
 * Generated at: 2021-05-30 07:49:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class userLoginPage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/Program%20Files/Apache%20Software%20Foundation/Tomcat%208.5/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("file:/C:/Program%20Files/Apache%20Software%20Foundation/Tomcat%208.5/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1620622623430L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>로그인 페이지</title>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">\n");
      out.write("    <title>TakeYourTime</title>\n");
      out.write("\t<link rel=\"stylesheet\" href=\"css/components/loginPage.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/reset.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/animate.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://use.fontawesome.com/releases/v5.7.0/css/all.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/common.css\">\n");
      out.write("    <link rel=\"shortcut icon\" sizes=\"76x76\" type=\"image/x-icon\"\n");
      out.write("        href=\"https://a0.muscache.com/airbnb/static/logotype_favicon-21cc8e6c6a2cca43f061d2dcabdf6e58.ico\">\n");
      out.write("    <script src=\"js/jquery-3.5.1.min.js\"></script>\n");
      out.write("    <script src=\"js/slick.min.js\"></script>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\t");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write(" \n");
      out.write("\t<header id=\"header\">\n");
      out.write("        <div class=\"topmenu\">\n");
      out.write("            <div class=\"row\">\n");
      out.write("                <a href=\"#none\"><i class=\"fab fa-facebook-square\"></i></a>\n");
      out.write("                <a href=\"#none\"><i class=\"fab fa-twitter\"></i></a>\n");
      out.write("                <a href=\"#none\"><i class=\"fab fa-instagram\"></i></a>\n");
      out.write("                <a href=\"#none\"><i class=\"fas fa-comment-dots\"></i></a>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"menubar row\">\n");
      out.write("            <div class=\"logo cf\">\n");
      out.write("                <!-- <svg viewBox=\"0 0 1000 1000\" role=\"presentation\" aria-hidden=\"true\" focusable=\"false\"\n");
      out.write("                        style=\"height: 1em; width: 1em; display: inline-block; fill: currentcolor;\">\n");
      out.write("                        <path\n");
      out.write("                            d=\"m499.3 736.7c-51-64-81-120.1-91-168.1-10-39-6-70 11-93 18-27 45-40 80-40s62 13 80 40c17 23 21 54 11 93-11 49-41 105-91 168.1zm362.2 43c-7 47-39 86-83 105-85 37-169.1-22-241.1-102 119.1-149.1 141.1-265.1 90-340.2-30-43-73-64-128.1-64-111 0-172.1 94-148.1 203.1 14 59 51 126.1 110 201.1-37 41-72 70-103 88-24 13-47 21-69 23-101 15-180.1-83-144.1-184.1 5-13 15-37 32-74l1-2c55-120.1 122.1-256.1 199.1-407.2l2-5 22-42c17-31 24-45 51-62 13-8 29-12 47-12 36 0 64 21 76 38 6 9 13 21 22 36l21 41 3 6c77 151.1 144.1 287.1 199.1 407.2l1 1 20 46 12 29c9.2 23.1 11.2 46.1 8.2 70.1zm46-90.1c-7-22-19-48-34-79v-1c-71-151.1-137.1-287.1-200.1-409.2l-4-6c-45-92-77-147.1-170.1-147.1-92 0-131.1 64-171.1 147.1l-3 6c-63 122.1-129.1 258.1-200.1 409.2v2l-21 46c-8 19-12 29-13 32-51 140.1 54 263.1 181.1 263.1 1 0 5 0 10-1h14c66-8 134.1-50 203.1-125.1 69 75 137.1 117.1 203.1 125.1h14c5 1 9 1 10 1 127.1.1 232.1-123 181.1-263.1z\">\n");
      out.write("                        </path>\n");
      out.write("    \t                <h2>Take Your Time</h2>\n");
      out.write("                    </svg> -->\n");
      out.write("                <h1><a href=\"home.do\">LOGO</a></h1>\n");
      out.write("            </div>\n");
      out.write("            <nav>\n");
      out.write("                <ul>\n");
      out.write("                    <!-- <li><a href=\"userBeMentorPage.jsp\">마스터가 되어보세요</a></li> -->\n");
      out.write("                        <li><a href=\"visitorShowHelpPage.jsp\">도움말</a></li>\n");
      out.write("                        <li><a href=\"userSignUpPage.jsp\">회원가입</a></li>\n");
      out.write("                        <li><a href=\"userLoginPage.jsp\">로그인</a></li>\n");
      out.write("                        <!-- <li><a href=\"#article2\">Force</a></li>\n");
      out.write("                        <li><a href=\"#article4\">Master</a></li>\n");
      out.write("                        <li><a href=\"#article5\"></a></li>\n");
      out.write("                        <li><a href=\"#none\">도움말</a></li> -->\n");
      out.write("                </ul>\n");
      out.write("            </nav>\n");
      out.write("        </div>\n");
      out.write("    </header>\n");
      out.write("    \t\n");
      out.write("    \t<br>\n");
      out.write("    \t<br>\n");
      out.write("    \t<br>\n");
      out.write("    \t<br>\n");
      out.write("    \t<br>\n");
      out.write("    \t<br>\n");
      out.write("    \t<br>\n");
      out.write("    \t<br>\n");
      out.write("    \t<br>\n");
      out.write("    \t<br>\n");
      out.write("    \t\n");
      out.write("    \t<div class=\"container\">\n");
      out.write("        <div class=\"login-details\">\n");
      out.write("            <h2>May the Force Be With You</h2>\n");
      out.write("            <p>Enter your personal detail to login </p>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"login-box\">\n");
      out.write("                <div class=\"user-box\">\n");
      out.write("                    <span>Take</span><br>\n");
      out.write("                    <span>Your</span><br>\n");
      out.write("                    <span>Force</span><br>\n");
      out.write("                    <!-- 상단 내용 -->\n");
      out.write("                </div>\n");
      out.write("                <form action=\"userLoginPage.do\" method=\"post\" name=\"loginForm\">\n");
      out.write("                    \n");
      out.write("                    <input type=\"text\" name=\"userid\" placeholder=\"아이디를 입력해 주세요!\">\n");
      out.write("                    \n");
      out.write("                    <input type=\"password\" name=\"userpw\" placeholder=\"비밀번호를 입력해 주세요!\">   \n");
      out.write("                    <input type=\"submit\" name=\"submit\" value=\"login\">\n");
      out.write("                      <a href=\"userSignUpPage.jsp\">회원가입하기</a>\n");
      out.write("                      <a href=\"userFindId.jsp\">Forget ID</a>\n");
      out.write("                      <a href=\"userFindPw.jsp\">Forget PW</a>\n");
      out.write("                </form>\n");
      out.write("            </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("\t\t  <!-- <div class=\"slogan\">\n");
      out.write("    \t\tThe force <br>&nbsp;&nbsp;&nbsp; are<br> awaken\n");
      out.write("    \t\t</div>\n");
      out.write("\t\t  <div class=\"cont\">\n");
      out.write("\t        <div class=\"demo\">\n");
      out.write("\t          <div class=\"login\">\n");
      out.write("\t            <div class=\"login__check\">\n");
      out.write("\t                <span>&nbsp;&nbsp;&nbsp;Login</span><br>\n");
      out.write("\t                <span>to</span><br>\n");
      out.write("\t                <span>Take your Force</span>\n");
      out.write("\t            </div>\n");
      out.write("\t            <form action=\"userLoginPage.do\" method=\"post\" name=\"loginForm\" onsubmit=\"\">\n");
      out.write("\t                <div class=\"login__form\">\n");
      out.write("\t                <div class=\"login__row\">\n");
      out.write("\t                    <svg class=\"login__icon name svg-icon\" viewBox=\"0 0 20 20\">\n");
      out.write("\t                    <path d=\"M0,20 a10,8 0 0,1 20,0z M10,0 a4,4 0 0,1 0,8 a4,4 0 0,1 0,-8\" />\n");
      out.write("\t                    </svg>\n");
      out.write("\t                    <input type=\"text\" class=\"login__input name\" placeholder=\"UserId\" name=\"userid\"/>\n");
      out.write("\t                </div>\n");
      out.write("\t                <div class=\"login__row\">\n");
      out.write("\t                    <svg class=\"login__icon pass svg-icon\" viewBox=\"0 0 20 20\">\n");
      out.write("\t                    <path d=\"M0,20 20,20 20,8 0,8z M10,13 10,16z M4,8 a6,8 0 0,1 12,0\" />\n");
      out.write("\t                    </svg>\n");
      out.write("\t                    <input type=\"password\" class=\"login__input pass\" placeholder=\"Password\" name= \"userpw\"/>\n");
      out.write("\t                </div>\n");
      out.write("\t                <input type=\"submit\" class=\"login__submit\" value=\"Login\"/>\n");
      out.write("\t                <p class=\"login__signup\">아직 회원이 아니신가요? &nbsp;<a href=\"userSignUpPage.jsp\">회원가입하기</a></p>\n");
      out.write("\t                <p class=\"login__signup login__findIdPw\">ID 를 잃어버리셨나요? &nbsp;<a href=\"userFindId.jsp\"> Id 찾기</a></p>\n");
      out.write("\t                <p class=\"login__signup login__findIdPw\">PW 를 잃어버리셨나요? &nbsp;<a href=\"userFindPw.jsp\"> PW 찾기</a></p>\n");
      out.write("\t                </div>\n");
      out.write("\t            </form>\n");
      out.write("\t          </div>\n");
      out.write("\t          </div>\n");
      out.write("\t     \t</div> -->\n");
      out.write("\t     \t\n");
      out.write("\t     \t\n");
      out.write("\t     \t<footer id=\"footer\">\n");
      out.write("        \t<div class=\"row\">\n");
      out.write("            <p>\n");
      out.write("                <a href=\"#none\">회사소개</a>\n");
      out.write("                <a href=\"#none\">사업분야</a>\n");
      out.write("                <a href=\"#none\">갤러리</a>\n");
      out.write("                <a href=\"#none\">온라인문의</a>\n");
      out.write("                <a href=\"#none\">고객센터</a>\n");
      out.write("            </p>\n");
      out.write("            <p><span>주소 : 부산광역시 해운대구 좌동 273-10</span> <span class=\"hide\"> / </span> <span>상호 : 디자인선사인</span> <span\n");
      out.write("                    class=\"hide\"> / </span>사업자등록번호 : 123-456-7890<br>\n");
      out.write("                <a href=\"tel:070-7155-19749\">Tel : 070-7155-19749</a> <span class=\"hide\"> / </span><span>Fax :\n");
      out.write("                    02-2139-1142</span> <span class=\"hide\"> / </span><a href=\"mailto:gijung23@nate.com\">E-mail :\n");
      out.write("                    gijung23@nate.com</a></p>\n");
      out.write("            <p>Copyright &copy; Sunsine.com All Rights Reserved.</p>\n");
      out.write("        </div>\n");
      out.write("    </footer>\n");
      out.write("\t     \t\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /userLoginPage.jsp(24,1) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userid == '' } && ${ !empty loginResult}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("\t\n");
          out.write("\t\t<script>\n");
          out.write("\t\t\n");
          out.write("\t\t\talert(\"아이디 혹은 비밀번호가 틀렸습니다.\");\n");
          out.write("\t\t\t\n");
          out.write("\t\t</script>\n");
          out.write("\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }
}
